[tool.poetry]
name = "gpt2giga"
version = "0.0.14"
description = ""
authors = ["Konstantin Krestnikov <rai220@gmail.com>"]
license = "MIT"
readme = "README.md"
include = [{ path = "data/gpt2giga_models.json", format = ["sdist", "wheel"] }]

[tool.poetry.dependencies]
python = "^3.10"
gigachat = "^0.1.42"
asyncio = "^3.4.3"
python-dotenv = "^1.0.1"
aiohttp = "^3.10.10"
tiktoken = "^0.9.0"
pillow = "^11.1.0"
openai = "^2.2.0"
ruff = "^0.13.3"
pydantic-argparse = "^0.10.0"
pydantic-settings = "^2.11.0"
fastapi = "^0.118.2"
uvicorn = "^0.37.0"


[tool.poetry.scripts]
gpt2giga = "gpt2giga:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
