http:
  routers:
    gpt2giga:
      entryPoints:
        - gpt2giga
      service: gpt2giga
      rule: PathPrefix(`/`)
  services:
    gpt2giga:
      loadbalancer:
        servers:
          - url: http://gpt2giga:8090
