http:
  routers:
    gpt2giga-pro:
      entryPoints:
        - gpt2gigapro
      service: gpt2giga-pro
      rule: PathPrefix(`/`)
  services:
    gpt2giga-pro:
      loadbalancer:
        servers:
          - url: http://gpt2giga_pro:8090
